name: GlobalWarming
author: poma123
description: 黏液科技附加 全球暖化 繁體翻譯版.
main: me.poma123.globalwarming.GlobalWarmingPlugin
website: https://github.com/poma123/GlobalWarming
depend: [Slimefun]
version: ${project.version}
api-version: 1.14

commands:
  globalwarming:
    description: GlobalWarming command
    aliases: gw
permissions:
  globalwarming.command.pollution:
    description: Allows you to manually change the pollution amount
    default: op
